### PR TITLE
Update for InkScape 1.0 - strange

### PR DESCRIPTION
**Pull request by vmario89**
To make it work with Python 3.8.5 on Windows and InkScape 1.1dev i did some adjustments.
Basically you need to install lxml, Pillow, numpy, scipy and opencv-python on Python 3.8.5 using pip. You cannot use the bundled Python of InkScape because it will say that it cannot install the modules. Instead you need to install Python from Homepage. You need to change the default python interpreter from InkScape in preferences.xml and to restart InkScape then.

```
  <group
     id="extensions"
     python-interpreter="C:\Users\you\AppData\Local\Programs\Python\Python38\python.exe"
```

the extension should run.

finally i got some results but they look strange. like this:
grafik

grafik

grafik

grafik

not sure how it looked in the past or what kind of graphics i need to put in to get something "nice"

### CODE REVIEW

**Comment by vmario89** [comment]
grafik
grafik

okay i think its not that bad :D

**Comment by Moini** [comment]
@vmario89 I think it is possible to use the Python that comes with Inkscape on Windows to install more modules. It includes pip, and it's supposed to work.

Can you message Patrick (@ede123 in Inkscape's chat, on GitLab and on GitHub) if you'd like to have help with instructions?

**Comment by vmario89** [comment]
hi again Moini!

 thanks for the tip. I just wrote him an email :-)

regards, Mario

**Comment by Moini** [comment]
Admittedly, I had a hidden agenda to have the info added to the FAQ on the Inkscape website - so, if/when you have a text description about how to install more Python modules on Windows, I'd like to get a copy for the FAQ :pleading_face: <- That smiley is supposed to be a pleading face ;-)

**Comment by Moini** [comment]
I still get a deprecation warning with your version, @vmario89 .

```
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
~/.config/inkscape/extensions/drawing_utils.py:41: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  'style' : simplestyle.formatStyle(style),
~/.config/inkscape/extensions/drawing_utils.py:45: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  path = inkex.etree.SubElement(parent, inkex.addNS('path','svg'), attribs)
```

Did the 'gradient' option ever work? It appears to be sampling just a tiny area of the image, judging from the result.

All in all, the results aren't very convincing for this extension :-/ (my test case was a bit difficult, of course)

Bildschirmfoto_2020-08-06_19-09-34
.

**Comment by vmario89** [comment]
Hey,
sorry for late reply. I just messed a bit more with code and could fix some things. made it working for linked and embedded images as well and added some try-catch. updated in https://github.com/vmario89/triangulate and PR

grafik
grafik
grafik

**Comment by Moini** [comment]
Confirmed that it works with linked images now.

When I run it, I get the cryptic error message

`/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
`

It still works, though.

Is there some module that I'm missing?

**Comment by vmario89** [comment]
hey Moini =) öööööööööhm no idea about this error. looks a bit generic - maybe some dependency problem or outdated lib like lxml?

does not happen on my instance. i am working with native installed Python 3.8.5 and configured inscape to use this python from %PATH%. when i have more time i will check out the python from inkscape (which should be at least 3.7 or 3.8 in official release though).

hopefully i will make some linux machine soon too to check out what happens with this and other extension on the unix world

**Comment by Moini** [comment]
Guess it's not so important, as it says it's using a fallback and still works. Don't worry about it. Some day I'll be on an Ubuntu 20.04 base, and hopefully, that error will then be gone.

**Pull request merged**
